Audio message support
Limvot/Serif pull request #37
Opened 2021-03-10 05:41 UTC by lotusronin

Fixes #30 

Based on the work in the Image Event Support branch. Supports better deserialization of audio room message events and adds support for displaying and attempting to play those events in the swing GUI. Made the SharedUiMessage class into a parent class with more specialized media type messages as derived classes.

2021-03-12 18:56 UTC, Limvot requested changes
I like it! I only have two requested changes, removing the extra serializer indirection and splitting out sendMessage into sendTextMessage and sendImageMessage. I like your class/inheritance design a lot!

2021-03-12 18:56 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Database.kt
> +        val file = File.createTempFile("media_", "img", cache_path)
Should we update the "img" part?

2021-03-12 18:56 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/States.kt
> +    fun sendMessage(msg: String, is_img: Boolean = false): MatrixState {
I think we should probably just split up sendMessage here, like we do at the MatrixSession level, instead of passing a boolean.

2021-03-12 18:56 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Events.kt
> +            else -> FallbackRMECSerializer
I think you don't need the indirection and these can just be TextRMEC.serializer() without going through TextRMECSerializer, etc

2021-03-12 18:56 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Events.kt
> +object FallbackRMECSerializer : GenericJsonRMECSerializer<FallbackRMEC>(FallbackRMEC.serializer())
And these could then go away...

2021-03-12 18:56 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Events.kt
> +}
And this too!

2021-03-13 00:29 UTC, lotusronin commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Events.kt
> +            else -> FallbackRMECSerializer
Good call!

2021-03-13 00:29 UTC, lotusronin commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Events.kt
> +object FallbackRMECSerializer : GenericJsonRMECSerializer<FallbackRMEC>(FallbackRMEC.serializer())
love deleting code

2021-03-13 00:30 UTC, lotusronin commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Events.kt
> +}
still love deleting code!

2021-03-13 03:37 UTC, lotusronin commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Database.kt
> +        val file = File.createTempFile("media_", "img", cache_path)
Update it to be a string per media type? The actual file extension? leave it off completely?

2021-03-13 04:09 UTC, lotusronin commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/States.kt
> +    fun sendMessage(msg: String, is_img: Boolean = false): MatrixState {
Yeah, and we will have to do that once we start supporting sending more message types

2021-03-14 23:40 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Database.kt
> +        val file = File.createTempFile("media_", "img", cache_path)
actual file extension makes sense to me, but it's not super important!

2021-03-14 23:45 UTC, Limvot approved these changes
Approve pending my tiny fix which I'm about to push

2021-03-14 23:45 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Events.kt
> +    override fun selectDeserializer(element: JsonElement) = element.jsonObject["msgtype"]!!.jsonPrimitive.content.let { type ->
This should be `element.jsonObject["msgtype"]?.jsonPrimitive?.content?.let` to account for redacted messages - I've got this locally and it fixes it - I can push it here and will mark resolved.

2021-03-20 19:05 UTC, vwroddy approved these changes

2021-03-20 19:07 UTC, merged