Initial rough spaces implementation - removed the concept of a rooms …
Limvot/Serif pull request #71
Opened 2021-06-14 04:34 UTC by Limvot

…list, now everything is like a chat room, since that's what spaces are anyway, and the room list is just a fake space. Not currently sorting or anything, but the links work, and it builds a room_id path that you can back out of.

Closes #70 .

THIS IS A DRAFT

2021-07-17 21:28 UTC, lotusronin requested changes
Remove unnecessary UI elements for the space view. Would also like to deduplicate the unread message counts.

2021-07-17 21:28 UTC, lotusronin commented on serif_swing/src/main/kotlin/serif_swing/App.kt
> +                //new_state is MatrixRooms && s is SwingRooms -> { s.update(new_state); return; }
Remove this comment

2021-07-17 21:28 UTC, lotusronin commented on serif_swing/src/main/kotlin/serif_swing/App.kt
> +            //is MatrixRooms -> SwingRooms(::transition, panel, mstate)
Remove this comment

2021-07-18 18:04 UTC, enoxone approved these changes

2021-07-24 20:49 UTC, lotusronin approved these changes
lgtm :+1:

2021-07-24 23:27 UTC, lotusronin approved these changes
new cache looks good!

2021-07-25 02:55 UTC, merged