Mentions UI
Limvot/Serif pull request #98
Opened 2021-06-27 05:55 UTC by lotusronin

Initial work for supporting mentions in the desktop version of Serif.

Fixes #97

2021-07-31 20:58 UTC, Limvot requested changes

2021-07-31 20:58 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/Events.kt
> +    constructor(body: String, rel_to: RelationBlock?, format: String, formatted_body: String) : this(
I think I'd remove the format param and make formatted_body nullable, and if it's non-null assign it with the hardcoded format.

2021-07-31 20:58 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/MatrixClient.kt
> +    fun sendMessage(msg: String, room_id: String, reply_id: String = "", format: String = "", formatted_body: String = ""): Outcome<String> {
That would make this just have a nullable formatted_body

2021-07-31 20:58 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/MatrixClient.kt
> +        val body = if(format == "") { TextRMEC(msg, relation) } else { TextRMEC(msg,relation,format,formatted_body) }
and allow you to remove this if

2021-07-31 20:58 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/MatrixClient.kt
> +    fun getRoomMembers(id: String): List<String> {
As we mentioned, this should be pushed down so it can be shared with room names pr

2021-07-31 20:58 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/States.kt
> +        val link_regex = Regex("<a href=\"https://matrix.to/#/[^:]*:[^>]*\">(.*)</a>")
This is great, but the Regex value should be pulled out of the function so it doesn't get re-created all the time

2021-07-31 20:58 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/States.kt
> +    fun sendMessage(msg: String, format: String = ""): MatrixState {
I guess this would make format a bool, though we could almost  remove it entirely and see if msg == getUnformattedBody(msg)

2021-07-31 20:58 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/States.kt
> +    fun sendReply(msg: String, in_reply_to_id: String, format: String = ""): MatrixState {
Ditto with above

2021-07-31 20:58 UTC, Limvot commented on serif_shared/src/commonMain/kotlin/xyz/room409/serif/serif_shared/States.kt
> +            val prev_content = event.message
We should prob expose formatted_message, and have this be copied into the formatted reply

2021-07-31 20:58 UTC, Limvot commented on serif_swing/src/main/kotlin/serif_swing/App.kt
> +    var formatted = false
If we do go with the getUnformattedBody changes thing way, we can remove this! Which I'm getting more on board with

2021-07-31 20:58 UTC, Limvot commented on serif_swing/src/main/kotlin/serif_swing/App.kt
> +            if(formatted && !message_field.text.contains("<a href=\"")) {
Handling whether or not it's formatted lower would also make this unnecessary

2021-07-31 20:58 UTC, Limvot commented on serif_swing/src/main/kotlin/serif_swing/App.kt
> +            val format = if(!formatted) { "" } else { "org.matrix.custom.html" }
ditto

2021-07-31 21:53 UTC, enoxone approved these changes

2021-08-02 04:49 UTC, Limvot approved these changes

2021-08-02 04:51 UTC, merged